version: '3.8'

services:
  # Tu aplicaci√≥n Django
  web:
    build: .
    container_name: sat_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000" # Mapeamos puerto 80 del servidor al 8000 de Gunicorn
    depends_on:
      - db
    env_file:
      - .env

  # La Base de Datos (Aislada, nueva y limpia)
  db:
    image: postgres:13-alpine
    container_name: sat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: